const screens=document.querySelectorAll('.screen');const navButtons=document.querySelectorAll('[data-screen]');const reader=document.querySelector('#readerScreen');const sheet=document.querySelector('#fundSheet');const toast=document.querySelector('#toast');let toastTimer;
function showToast(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2100)}
function showScreen(name){reader.hidden=true;screens.forEach(screen=>{const selected=screen.id===`${name}Screen`;screen.hidden=!selected;screen.classList.toggle('active',selected)});navButtons.forEach(button=>{const selected=button.dataset.screen===name;button.classList.toggle('active',selected);selected?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'smooth'})}
navButtons.forEach(button=>button.addEventListener('click',()=>showScreen(button.dataset.screen)));
document.querySelectorAll('.feed-tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.feed-tabs button').forEach(item=>item.classList.toggle('active',item===button));showToast(button.textContent==='Latest'?'Showing the latest reports':'Showing journalists you follow')}));
function openReader(){reader.hidden=false;reader.scrollTop=0;window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#openLeadStory').addEventListener('click',openReader);document.querySelector('#openLeadStory').addEventListener('keydown',event=>{if(event.key==='Enter')openReader()});document.querySelector('#closeReader').addEventListener('click',()=>{reader.hidden=true});document.querySelector('.save-reader').addEventListener('click',event=>{event.currentTarget.textContent='Saved';showToast('Saved to your reading list')});
function openFundSheet(){sheet.hidden=false;document.body.style.overflow='hidden'}function closeFundSheet(){sheet.hidden=true;document.body.style.overflow=''}
document.querySelector('#openFundSheet').addEventListener('click',openFundSheet);document.querySelector('#briefingFund').addEventListener('click',()=>{showScreen('fund');setTimeout(openFundSheet,180)});document.querySelector('#closeFundSheet').addEventListener('click',closeFundSheet);sheet.addEventListener('click',event=>{if(event.target===sheet)closeFundSheet()});document.querySelectorAll('.amounts button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.amounts button').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('.amount input').value=button.textContent.replace('₿','')}));
document.querySelector('#connectWallet').addEventListener('click',()=>showToast('Bitcoin wallet connection will open here'));document.querySelector('#howFundWorks').addEventListener('click',()=>showToast('Every payout requires a verified reporting milestone'));document.querySelector('#previewArticle').addEventListener('click',()=>showToast('Article preview ready'));document.querySelector('#publishArticle').addEventListener('click',()=>showToast('Encrypted draft is ready to publish'));document.querySelector('#settingsButton').addEventListener('click',()=>showToast('Protected settings will open here'));document.querySelector('#withdrawButton').addEventListener('click',()=>showToast('Bitcoin withdrawal will open here'));document.querySelector('#historyButton').addEventListener('click',()=>showToast('Showing 6 verified payouts'));document.querySelectorAll('.quick-stories button').forEach(button=>button.addEventListener('click',()=>showToast(`${button.querySelector('strong').textContent} report will open here`)));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!sheet.hidden)closeFundSheet();else if(event.key==='Escape'&&!reader.hidden)reader.hidden=true});
